version: '2.1'

services:
  postgres:
    container_name: "${COMPOSE_PROJECT_NAME:-django-multitenant}_postgres"
    image: 'postgres:${POSTGRES_VERSION:-17}'
    ports: [ '5600:5432' ]
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    command: -c fsync=off -c full_page_writes=off
