name: "Django Multitenant Tests"
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - uses: actions/checkout@v3
    - name: Install python dependencies
      run: |
        pip install -r requirements/static-analysis-requirements.txt
    - name: Format Checks
      run: |
        make format-check
    - name: Prospector checks
      run: |
        make lint

    - name: Documentation Checks
      run: |
        cd docs
        sphinx-build -W -b html source builds

  tests:
    runs-on: ubuntu-latest
    name: "Python: ${{matrix.python_version}} | Django: ${{matrix.django_version}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - { django_version: "4.2", python_version: "3.10" }
          - { django_version: "4.2", python_version: "3.11" }
          - { django_version: "4.2", python_version: "3.12" }
          - { django_version: "5.2", python_version: "3.10" }
          - { django_version: "5.2", python_version: "3.11" }
          - { django_version: "5.2", python_version: "3.12" }
          - { django_version: "5.2", python_version: "3.13" }
          - { django_version: "5.2", python_version: "3.14" }
          - { django_version: "6.0", python_version: "3.12" }
          - { django_version: "6.0", python_version: "3.13" }
          - { django_version: "6.0", python_version: "3.14" }
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    env:
      DJANGO_VERSION: ${{ matrix.django_version }}
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install test dependencies
      run: |
        make test-dependencies
    - name: Test Django MT
      run: |
        make test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
    - name: Test Missing Modules
      run: |
        make test-missing-modules
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
